#!/bin/bash
rails g migration remove_logo_content_type_from_deal_builder logo_content_type:string
rails g migration remove_logo_file_size_from_deal_builder logo_file_size:integer
rails g migration remove_logo_updated_at_from_deal_builder logo_updated_at:datetime
rails g migration remove_offer_value_from_deal_builder offer_value:integer
rails g migration remove_offer_price_from_deal_builder offer_price:integer
rails g migration remove_offer_description_from_deal_builder offer_description:text
rails g migration remove_industry_from_deal_builder industry:string
rails g migration remove_offer_photo_file_name_from_deal_builder offer_photo_file_name:string
rails g migration remove_offer_photo_content_type_from_deal_builder offer_photo_content_type:string
rails g migration remove_offer_photo_file_size_from_deal_builder offer_photo_file_size:integer
rails g migration remove_offer_photo_updated_at_from_deal_builder offer_photo_updated_at:datetime
rails g migration remove_submit_for_review_from_deal_builder submit_for_review:string
rails g migration remove_optional_restriction_from_deal_builder optional_restriction:text
rails g migration remove_optional_incentive_from_deal_builder optional_incentive:text
rake db:migrate
rails destroy migration remove_logo_content_type_from_deal_builder logo_content_type:string
rails destroy migration remove_logo_file_size_from_deal_builder logo_file_size:integer
rails destroy migration remove_logo_updated_at_from_deal_builder logo_updated_at:datetime
rails destroy migration remove_offer_value_from_deal_builder offer_value:integer
rails destroy migration remove_offer_price_from_deal_builder offer_price:integer
rails destroy migration remove_offer_description_from_deal_builder offer_description:text
rails destroy migration remove_industry_from_deal_builder industry:string
rails destroy migration remove_offer_photo_file_name_from_deal_builder offer_photo_file_name:string
rails destroy migration remove_offer_photo_content_type_from_deal_builder offer_photo_content_type:string
rails destroy migration remove_offer_photo_file_size_from_deal_builder offer_photo_file_size:integer
rails destroy migration remove_offer_photo_updated_at_from_deal_builder offer_photo_updated_at:datetime
rails destroy migration remove_submit_for_review_from_deal_builder submit_for_review:string
rails destroy migration remove_optional_restriction_from_deal_builder optional_restriction:text
rails destroy migration remove_optional_incentive_from_deal_builder optional_incentive:text

